### PR TITLE
Add declare namespace

### PR DESCRIPTION
**Pull request by unional**
This allows user to use the  `import * as Promise from 'any-promise';`

### CODE REVIEW

**Comment by unional** [comment]
https://github.com/palantir/tslint/pull/1016#discussion_r58152504
@JKillian, I tried to do what you suggested back in the `extends` feature here, but in this case it doesn't work. 

After the change, I can do `import * as Promise from 'any-promise';`
but when I try to use it:
image

Any idea?

**Comment by jkillian** [comment]
If you can do `import * as Promise from 'any-promise';`, you should definitely be able to use the `Promise` identifier in your code... maybe an IDE issue?

**Comment by unional** [comment]
Interesting. I do see it is working like you said.

Will file an issue on `vscode` and likely `tsc`

**Comment by blakeembrey** [comment]
I don't intend to support this, it's a hack and not valid ES6.

**Comment by unional** [comment]
Argee to your direction.

For reference, currently the only way to import this library in ES6 syntax is either:
- `module: "commonjs"` + `allowSyntheticDefaultImports: "true"`, or
- `module: "system"`

and Thus connects to https://github.com/Microsoft/TypeScript/issues/7398

**Comment by blakeembrey** [comment]
@unional Sorry that previous post was a little brief/harsh, I know we've had the discussion before 😄 I don't think we should be forcing non-ES6 imports into an ES6 syntax, it's just not possible unless TypeScript intends to emit the correct transformations at the JavaScript level (E.g. emit `x = require('x')` instead of `x = require('x').default`). For the correct transformations to be emitted, we'd need accurate type definitions anyway, and that's not the ES6 construct you'd be using.

**Comment by unional** [comment]
It's all good. I said in the past that I was trying to setup the environment / framework in my company and one thing I tried to avoid is forcing them to understand and use both `require()` and `import ... from ...`.

But as you know we discover the issue of the interop and today I'm "officially" abandoning that idea:

https://github.com/unional/typescript/blob/master/style-guide/default/modules.md#import-keyword

:tulip:

**Pull request closed without merging**
